### ISSUE TITLE
YQ 4+ required but script doesn't proceed

### ISSUE THREAD

**Issue by Megatron1024** [dynatrace-oss/dynatrace-gcp-function#150]
Folks,

First of all the instructions here: https://www.dynatrace.com/support/help/shortlink/deploy-gcp downloads version 3.x.x of yq

Secondly, the script doesn't allow the installation without version 4+

Then after installing yq version 4+, the script still fails... Take a look here:

![image](https://user-images.githubusercontent.com/19298968/128666587-5d8257dc-0d4a-4cb3-961b-32ae66efd9ed.png)

**Comment by karolkieglerski** [comment]
@Megatron1024 please install this correct version: https://github.com/mikefarah/yq/releases/tag/v4.9.8, after that version thay changed versioning and version is not correct showing for our script. Thanks for heads up we will update our documentation

**Comment by karolkieglerski** [comment]
from that issue we created bug APM-318067. Documentation will be updated with fixed version for `yq` set to v4.9.8
