### ISSUE TITLE
GCP Integration creates infinite dashboards

### ISSUE THREAD

**Issue by joostschriek** [dynatrace-oss/dynatrace-gcp-function#161]
https://github.com/dynatrace-oss/dynatrace-gcp-function/blob/1150562f5095471b126896fc31d1300c1f95302c/src/lib/self_monitoring.py#L309-L311

Our GCP service account did not have the `monitoring.dashboards.list` permissions, because this _*is not listed anywhere in the dosc*_ nor is [it being created by the helm deployment package provided](https://github.com/dynatrace-oss/dynatrace-gcp-function/tree/1150562f5095471b126896fc31d1300c1f95302c/gcp_iam_roles).

Please also not that we had self_monitoring off, and we only notice dthe dashboards when we started peeking at audit logs.

If the result HTTP 403, like it was with us, this will just keep on creating dashboards until the quota is hit. 

```json
{
  "error": {
    "code": 403,
    "message": "The caller does not have permission",
    "status": "PERMISSION_DENIED"
  }
}
```

Removing it requires some annoying hop jumping

```bash
$ gcloud monitoring dashboards list > way_too_many_dashboards.yaml
$ docker run --rm -v "${PWD}":/workdir mikefarah/yq -N e 'select(.displayName == "dyna*") | .name' way_too_many_dashboards.yaml | xargs -n 1 gcloud monitoring dashboards delete --quiet
```

**Comment by sq2gxo** [comment]
@joostschriek thank you for report, we are working on fixing this bug and including in next release
