### ISSUE TITLE
Self Monitoring project

### ISSUE THREAD

**Issue by joostschriek** [dynatrace-oss/dynatrace-gcp-function#174]
Am i correct in assume that the selfMonitoring abilities of the gcp-function are specifically tied to a project name `'dynatrace-gcp-extension'`?

It seems that the [create metrics call](https://github.com/dynatrace-oss/dynatrace-gcp-function/blob/8890dc201136fc59975fdd92a9afb28fd58dd6ea/src/lib/self_monitoring.py#L133) will always default to the `context.project_owner_id` that is pass thru the MetricsContext from, initially, [`HandleEvent`](https://github.com/dynatrace-oss/dynatrace-gcp-function/blob/8890dc201136fc59975fdd92a9afb28fd58dd6ea/src/main.py#L62) in main.py that default it to `dynatrace-gcp-extension`. 

As far as I can see. this project is also being used to get the dynatrace api keys, which is odd to me because we don't have this project.

How do I direct this function to make the metrics in the GCP_PROJECT env variable specified project?

**Comment by sq2gxo** [comment]
Hi @joostschriek that looks like a bug, we will investigate it and release fix quickly
