### ISSUE TITLE
Vulnerabilities to be addressed

### ISSUE THREAD

**Issue by peijunzh** [dynatrace-oss/dynatrace-gcp-function#390]
With aqua/scanner:2022.4.217 to scan image dynatrace/dynatrace-gcp-monitor:release-1.1.0, there are two high issues found. Can those issues be fixed please?

<img width="1557" alt="image" src="https://user-images.githubusercontent.com/104785307/225051229-3474eaab-eb24-486d-9c89-690db5510038.png">

**Comment by joaquinfilipic-dynatrace** [comment]
The cryptography version has been bumped up already, next release will have it updated. It uses internally openssl, as I far as I know, so that scanned vulnerability should be linked (our explicit use of openssl is in scripts, outside the source code).
