### ISSUE TITLE
Least permission needed instead of complete role.

### ISSUE THREAD

**Issue by vikramsinghsaggu** [dynatrace-oss/dynatrace-gcp-function#45]
HI Team,

To enable sending metrics from CloudSQL service, below role is mentioned to be added on service account which has some additional permissions which may not needed for sending metrics. Same applies to other mentioned roles for rest of the services having additional permissions. 

Can we know what exact permissions are need for sending metrics rather than having the complete Role? 
There are some security concerns on using the full Role.

**roles/cloudsql.viewer**
 - cloudsql.*.export
 - cloudsql.*.get
 - cloudsql.*.list
 - cloudsql.instances.listServerCa

**Comment by pawelsiwek** [comment]
@vikramsinghsaggu  instead of using the preset of roles we've documented it should be enough to grant simply Viewer on the project level.  Will it help, or do You still expect precise list of permissions to build custom Role?

**Comment by mmajcher** [comment]
Closing due to missing input from issue author. Please contact us if issue is still relevant.
