### ISSUE TITLE
Metric unit mappings

### ISSUE THREAD

**Issue by jackstuart92** [dynatrace-oss/dynatrace-gcp-function#49]
Hey, I am trying to map metric units configured in the GCP service yaml files to the metric unit format in Dynatrace so that i can create custom alerts in the UI or via the API. Would you be able to help with the mappings containing "????" or point me in the right direction?

{
    "%"            : "Percentage",
    "10^2.%"       : "Percentage", // multiplies the value by 100 before ingestion
    "1"            : "Count",
    "ms"           : "MilliSecond",
    "s"            : "Second",
    "By"           : "Bytes",
    "GiBy"         : "GigaByte",
    ""             : "UNSPECIFIED",
    "{CPU}"        : "????",
    "{packets}"    : "????",
    "d"            : "????",
    "s"            : "Second",
    "us"           : "MicroSecond",
    "1/s"          : "PerSecond",
    "{connection}" : "????",
    "{request}"    : "????",
    "s{CPU}"       : "????",
    "By/s"         : "BytePerSecond",
    "GBy.s"        : "???? GigaBytes per second?",
    "GiBy.s"       : "???? GigaBytes per second?",
    "{inode}"      : "????",
    "{dBm}"        : "????",
    "ns"           : "NanoSecond",
    "s{idle}"      : "????",
    "s{uptime}"    : "????",
    "{port}"       : "????",
    "{packet}"     : "????",
    "{connection}" : "????"
}

Many thanks
Jack

**Comment by sq2gxo** [comment]
Hello Jack,

First of all I'm very sorry for late response.

You can find units mapping here: https://github.com/dynatrace-oss/dynatrace-gcp-function/blob/master/generate_metadata.py#L24

units not present in this map are set to `Unspecified`

Best,
Marek
