### ISSUE TITLE
Wrong token scopes

### ISSUE THREAD

**Issue by lkoniecki** [dynatrace-oss/dynatrace-gcp-function#6]
Documentation https://github.com/dynatrace-oss/dynatrace-gcp-function states that token with 
* API v2 Ingest metrics
* API v1 Read configuration

is required while Write configuration scope is required to write dashboards.

See error:

`- Create ["Google Cloud APIs"] dashboard from file [dashboards/api.json]
{"error":{"code":403,"message":"Token is missing required scope. Use one of: WriteConfig (Write configuration)"}}`

**Comment by pawelsiwek** [comment]
Thanks for reporting this, the fix is already on PR
