### ISSUE TITLE
Can not provide custom URL as a tenant URL

### ISSUE THREAD

**Issue by lkoniecki** [dynatrace-oss/dynatrace-gcp-function#7]
See: https://github.com/dynatrace-oss/dynatrace-gcp-function/blob/master/scripts/setup.sh

`while ! [[ "${DYNATRACE_URL}" =~ ^https:\/\/[a-z0-9-]{8}\.(live|sprint|dev)\.(dynatrace|dynatracelabs)\.com\/$ ]]; do
    read -p "Enter Dynatrace tenant URI: " DYNATRACE_URL
done`

script supports only SaaS tenant URLs. It does not support custom Cluster AG URL for managed.

**Comment by pawelsiwek** [comment]
Thanks for reporting the fix is already on PR waiting for review
