### ISSUE TITLE
Dataflow dimension breaching the metric ingestion API dimension character limit

### ISSUE THREAD

**Issue by jackstuart92** [dynatrace-oss/dynatrace-gcp-function#71]
I came across some dimensions that are breaching a character limit. I believe this error is returned by the metric ingestion API as an invalid line with the message on the exceeded length. Speaking with the project owner, they require the dimension and can’t truncate it on their end. Can we get this char limit increased to say 500 and as a fall back truncate the dimension if it is over that?
 
INVALID LINE: 'cloud.gcp.dataflow_googleapis_com.job.estimated_byte_count,job_id=" REDACTED ",pcollection="SpannerIO.Write/Write mutations to Cloud Spanner/Schema View/Combine.GloballyAsSingletonView/View.CreatePCollectionView/Combine.globally(Concatenate)/Combine.perKey(Concatenate)/GroupByKey+SpannerIO.Write/Write mutations to Cloud Spanner/Schema View/Combine.GloballyAsSingletonView/View.CreatePCollectionView/Combine.globally(Concatenate)/Combine.perKey(Concatenate)/Combine.GroupedValues/Partial.out0",job_name="REDACTED",region="europe- REDACTED",project_id="REDACTED" gauge,20755 1616588614000', reason: 'dimension value length exceeded: 401 > 250'

**Comment by jackstuart92** [comment]
@pawelsiwek

**Comment by Dawid-Kaszubski** [comment]
Hi @jackstuart92 ,
Right now we're not able to change constraints of dimension length for API. I'll prepare a change, which will truncate dimension if it over that limit.

**Comment by jackstuart92** [comment]
Sure, thanks @Dawid-Kaszubski
