### ISSUE TITLE
HTTPS_PROXY and HTTP_PROXY environment variables are not defined in the deployment or config map

### ISSUE THREAD

**Issue by jackstuart92** [dynatrace-oss/dynatrace-gcp-function#75]
The proxy environment variables are not set by the deployment YAML and likewise there are no parameters to set them in the config map.

https://github.com/dynatrace-oss/dynatrace-gcp-function/blob/master/k8s/dynatrace-gcp-function.yaml

**Comment by jackstuart92** [comment]
I have added these myself but thought i would bring to your attention that they are not configurable options
  
  # config map
  # to be used in conjunction with USE_PROXY. set the proxy address
  HTTPS_PROXY: "my.proxy.com:123"
  HTTP_PROXY: "my.proxy.com:123"
  
  # deployment
          - name: HTTP_PROXY
            valueFrom:
              configMapKeyRef:
                name: dynatrace-gcp-function-config
                key: HTTP_PROXY
          - name: HTTPS_PROXY
            valueFrom:
              configMapKeyRef:
                name: dynatrace-gcp-function-config
                key: HTTPS_PROXY

**Comment by Dawid-Kaszubski** [comment]
Thank you for pointing it out.
We will add these env variables to deployment YAML.
