### ISSUE TITLE
Setup script failing to create self-monitoring dashboards

### ISSUE THREAD

**Issue by 4lch4** [dynatrace-oss/dynatrace-gcp-function#96]
Heyo, folks.

We recently tried installing this function to our GCP environment only for it to fail to create the self-monitoring dashboards within GCP. This is the error we're seeing:

```bash
- create self monitoring dashboard
cat: dashboards/dynatrace-gcp-function_self_monitoring.json: No such file or directory
ERROR: (gcloud.monitoring.dashboards.list) Term operand expected [displayName: *HERE*].
ERROR: (gcloud.monitoring.dashboards.create) argument --config-from-file: Unable to read file [dashboards/dynatrace-gcp-function_self_monitoring.json]: [Errno 2] No such file or directory: 'dashboards/dynatrace-gcp-function_self_monitoring.json'
Usage: gcloud monitoring dashboards create (--config=CONFIG | --config-from-file=CONFIG_FROM_FILE) [optional flags]
  optional flags may be  --config | --config-from-file | --help
For detailed information on this command and its flags, run:
  gcloud monitoring dashboards create --help
- cleaning up
~
- removing archive [dynatrace-gcp-function.zip]
- removing temporary directory [dynatrace-gcp-function.zip]
```

It looks like the issue is on lines 276 & 280 of [setup.sh][0]. It's trying to pull the files from the dashboard folder but it's nowhere near that folder.

If this is only happening because we're attempting to install it incorrectly, then I believe the docs need to be updated to reflect this because we were simply following [these docs][1] and ran into this issue.

[0]: https://github.com/dynatrace-oss/dynatrace-gcp-function/blob/master/scripts/setup.sh
[1]: https://www.dynatrace.com/support/help/technology-support/cloud-platforms/google-cloud-platform/monitor-gcp-services-with-dynatrace/deploy-as-gcp-function/

**Comment by sq2gxo** [comment]
Hi Devin @4lch4 
Thank you for your report - we are checking the issue.
Are you deploying from Google Cloud Shell or in Bash?

**Comment by 4lch4** [comment]
This is using bash.

**Comment by sq2gxo** [comment]
Hi, I've reprocuded the issue.
It seem like there is no 'unzip' command in your environment.
Please install unzip and run again.
As a fix -I'll add test for unzip in installational script and also update prereuisities in docs.

**Comment by 4lch4** [comment]
> Hi, I've reproduced the issue.
> It seem like there is no 'unzip' command in your environment.
> Please install unzip and run again.
> As a fix -I'll add test for unzip in installational script and also update prereuisities in docs.

That was indeed it! Thank you so much for the quick assistance ^_^

I'd say this is good to close but I'll leave that decision up to you all.

**Comment by sq2gxo** [comment]
Great! I'll close this issue after merging additional checks for unzip to master.

**Comment by sq2gxo** [comment]
PR merged https://github.com/dynatrace-oss/dynatrace-gcp-function/pull/100
